name: Flutter CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: zip first.zip first.txt
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: first.zip
